### ISSUE TITLE
Club Details Page Map President ID to Name

### ISSUE THREAD

**Issue by devopsec** [devopsec/student_clubs#7]
president id is being shown on club details page but we need to show president name.
Use the query from the add modal that was already created

**Comment by thetechnician94** [comment]
Updated SQL query to pull name instead of ID

**Comment by devopsec** [comment]
Reopening this Issue, please commit your changes and reference the issue in your commit message, and it will automatically close on commit, or when your pull request is merged if you decided to fork the repo.

You can reference the issue using github markdown syntax like so:

```
resolves #7
```
